Numpy Assignment

In [53]:
import warnings
warnings.filterwarnings("ignore")

1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [1]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)
arr.shape

int32


(6,)

2. Given a NumPy array 'arr', check if its data type is float64.
  

In [ ]:
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype == np.float64)

True


3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


4. Convert an existing NumPy array 'arr' of integers to float32 data type

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(np.float32)
print(arr)

[1. 2. 3. 4. 5.]


5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
arr2 = np.array([1.5, 2.6, 3.7])
arr = arr2.astype(np.float32)
print(arr)

[1.5 2.6 3.7]


6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type

In [ ]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype
array_attributes(arr)

((3,), 3, dtype('float32'))

7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:
def array_dimension(arr):
    return arr.ndim
array_dimension(arr)

1

8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [ ]:
def item_size_info(arr):
    return "item size: ",arr.itemsize, "total size in bytes: ",arr.nbytes
arr = np.array([1, 2, 3, 4, 5])
item_size_info(arr)

('item size: ', 8, 'total size in bytes: ', 40)

9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
def array_strides(arr):
    return arr.strides
array_strides(arr)

(8,)

10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [ ]:
def shape_stride_relationship(arr):
    return arr.shape, arr.strides
shape_stride_relationship(arr)

((5,), (8,))

11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.

In [ ]:
def create_zeros_array(n):
    return np.zeros(n)

create_zeros_array(5)

array([0., 0., 0., 0., 0.])

12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

In [ ]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

create_ones_matrix(2, 4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [ ]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

generate_range_array(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

In [ ]:
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

generate_linear_space(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.

In [ ]:
def create_identity_matrix(n):
    return np.eye(n)

create_identity_matrix(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

16. Write a function that takes a Python list and converts it into a NumPy array.

In [ ]:
def python_list_to_numpy_array(lst):
    return np.array(lst)

python_list_to_numpy_array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
new_arr = arr1.view()  #numpy.view creates a new array object that shares the same data buffer as the original array. This means that any changes made to the view will also affect the original array, and vice versa.
print(new_arr)

[1 2 3 4 5]


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

concatenate_arrays(arr1,arr2,0)

array([1. , 2. , 3. , 4. , 5. , 1.5, 2.6, 3.7])

19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.

concatenate`.

In [ ]:
arr1 = np.array([1, 2, 3,7,5])
arr2 = np.array([4, 5, 6])
np.concatenate((arr1, arr2), axis=0)

array([1, 2, 3, 7, 5, 4, 5, 6])

20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
def vertical_stack(arr_list):
    return np.vstack(arr_list)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

vertical_stack([arr1, arr2])

array([[1, 2, 3],
       [4, 5, 6]])

21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.

In [ ]:
def create_integer_array(start, stop, step):
    return np.arange(start, stop, step)

create_integer_array(0, 10, 2)

array([0, 2, 4, 6, 8])

22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [ ]:
def create_equally_spaced_array(start, stop, num):
    return np.linspace(start, stop, num)

create_equally_spaced_array(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).

In [ ]:
def create_logarithmically_spaced_array(start, stop, num):
    return np.logspace(start, stop, num)

print(create_logarithmically_spaced_array(1, 1000, 5))

[1.00000000e+001 5.62341325e+250             inf             inf
             inf]


/usr/local/lib/python3.10/dist-packages/numpy/core/function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [ ]:
import pandas as pd
import numpy as np
data = np.random.randint(1, 101, size=(4, 3))
df = pd.DataFrame(data)
df

0   1   2
0   5  37  19
1  37   2  43
2   1  12  84
3  98  61  89

25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame

In [ ]:
def replace_negative_values(df, column_name):
    df.loc[df[column_name] < 0, column_name] = 0
    return df
df.columns=['a','b','c']
replace_negative_values(df ,'b' )

a   b   c
0   5  37  19
1  37   2  43
2   1  12  84
3  98  61  89

26. Access the 3rd element from the given NumPy array.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

27. Retrieve the element at index (1, 2) from the 2D NumPy array

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1,2]

6

28. Using boolean indexing, extract elements greater than 5 from the given NumPy array

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7])
arr[arr>5]

array([ 8, 10,  7])

29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

In [ ]:
def extract_elements(arr_2d, indices):
    return arr_2d[indices]
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
indices = np.array([0, 2])
extract_elements(arr_2d, indices)

array([[1, 2, 3],
       [7, 8, 9]])

def extract_elements(arr_2d, indices):
    return arr_2d[indices]
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
indices = np.array([0, 2])
extract_elements(arr_2d, indices)

In [ ]:
def extract_elements(arr_2d, indices):
    return arr_2d[indices]
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([0, 2])
extract_elements(arr_2d, indices)

array([[1, 2, 3],
       [7, 8, 9]])

33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [4]:
def extract_elements(arr_3d, indices_x, indices_y, indices_z):
    return arr_3d[indices_x, indices_y, indices_z]

arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
indices_x = np.array([0, 1])
indices_y = np.array([0, 1])
indices_z = np.array([0, 2])

print(extract_elements(arr_3d, indices_x, indices_y, indices_z))


[ 1 12]


34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.

In [6]:
def extract_elements(arr, condition1, condition2):
    return arr[(condition1 & condition2)]

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

condition1 = arr > 3
condition2 = arr % 2 == 0

print(extract_elements(arr, condition1, condition2))

[4 6 8]


35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [13]:
def extract_elements(arr_2d, row_indices, col_indices):
   return arr_2d[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(extract_elements(arr_2d,1,2 ))


6


36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [21]:
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr ," + ",5,"\n =\n ",arr+5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]  +  5 
 =
  [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [57]:
arr1=np.array([[1, 2, 3]])
arr1_reshape= arr1.T
arr2=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr1_reshape*arr2)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [56]:
arr1=np.array([[1, 2, 3, 4]])
arr1_reshape= arr1.T
arr2=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr1_reshape + arr2

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.


In [30]:
rr1=np.array([[1], [2], [3]])
arr2=np.array([[1, 2, 3]])
print(arr1+arr2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [42]:
arr1=np.array([[1, 2, 3], [4, 5, 6]])
arr2=np.array([[1, 2], [3, 4]])

reshaped_arr2 = np.pad(arr, ((0, 0), (0, 1)), mode='minimum')
reshaped_arr2*arr1

array([[ 1,  4,  3],
       [12, 20, 18]])

41. Calculate column wise mean for the given array:

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.mean(arr,axis=0)

array([2.5, 3.5, 4.5])

42. Find maximum value in each row of the given array

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr,axis=1)


array([3, 6])

43. For the given array, find indices of maximum value in each column.

In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.argmax(arr,axis=0)

array([1, 1, 1])

44. For the given array, apply custom function to calculate moving sum along rows.

In [11]:
def custom_sum_func(arr):
    return np.cumsum(arr,axis=1)

arr = np.array([[1, 2, 3], [4, 5, 6]])
custom_sum_func(arr)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

45. In the given array, check if all elements in each column are even.

In [12]:
arr = np.array([[2, 4, 6], [3, 5, 7]])

np.all(arr%2==0,axis=0)

array([False, False, False])

46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.

In [13]:
original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3
reshaped_matrix = original_array.reshape(m, n)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


47. Create a function that takes a matrix as input and returns the flattened array.

In [14]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = input_matrix.flatten()
print(flattened_array)

[1 2 3 4 5 6]


48. Write a function that concatenates two given arrays along a specified axis.

In [15]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array = np.concatenate((array1, array2), axis=1)
print(concatenated_array)

[[1 2 5 6]
 [3 4 7 8]]


49. Create a function that splits an array into multiple sub-arrays along a specified axis.

In [16]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_arrays = np.split(original_array, 3, axis=0)
print(sub_arrays)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


50. Write a function that inserts and then deletes elements from a given array at specified indices.

In [17]:
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

def insert(arr,indices,values,delete):
  new_arr = np.insert(arr,indices,values)
  return np.delete(new_arr,delete)

insert(original_array,indices_to_insert,values_to_insert,indices_to_delete)

array([ 1, 10,  4, 11,  5])

51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [22]:
import random
arr1 =np.array([random.randint(1, 10) for _ in range(5)])
arr2 =np.array([random.randint(1, 10) for _ in range(5)])
print(arr1," + ",arr2," = ",arr1+arr2)

[ 7  5  4  7 10]  +  [2 7 9 9 9]  =  [ 9 12 13 16 19]


52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [25]:
arr1 = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr1," - ",arr2," = ",arr1-arr2)

[10  9  8  7  6  5  4  3  2  1]  -  [ 1  2  3  4  5  6  7  8  9 10]  =  [ 9  7  5  3  1 -1 -3 -5 -7 -9]


53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [26]:
arr1 =np.array([random.randint(1, 10) for _ in range(5)])
arr2 =np.array([random.randint(1, 10) for _ in range(5)])
print(arr1," * ",arr2," = ",arr1*arr2)

[ 1  2  6 10  8]  *  [10 10 10  9  6]  =  [10 20 60 90 48]


54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [27]:
arr1 = np.array([2, 4, 6, 8, 10])
arr2 = np.array([1, 2, 3, 4, 5])
print(arr1," / ",arr2," = ",arr1/arr2)

[ 2  4  6  8 10]  /  [1 2 3 4 5]  =  [2. 2. 2. 2. 2.]


55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [33]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = arr1[::-1]
print(arr1," ** ",arr2," = ",arr1**arr2)

[1 2 3 4 5]  **  [5 4 3 2 1]  =  [ 1 16 27 16  5]


56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [34]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
def count_substring(arr, substring):
    count = 0
    for string in arr:
        if substring in string:
            count += 1
    return count
count_substring(arr, 'hello')

3

57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [35]:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def extract_uppercase(arr):
    uppercase_chars = []
    for string in arr:
        uppercase_chars.extend([char for char in string if char.isupper()])
    return np.array(uppercase_chars)
extract_uppercase(arr)

array(['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T'], dtype='<U1')

58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

In [40]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def replace_substring(arr, old_substring, new_substring):
    new_arr = []
    for string in arr:
        new_arr.append(string.replace(old_substring, new_substring))
        return np.array(new_arr)
print(replace_substring(arr, 'apple', 'orange'))

['orange']


60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [42]:
arr= np.array(['apple', 'banana', 'grape', 'pineapple'])
def find_longest_string(arr):
    longest_length = 0
    for string in arr:
        if len(string) > longest_length:
            longest_length = len(string)
    return longest_length,string
find_longest_string(arr)


(9, 'pineapple')

61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [43]:
import numpy as np

dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Mean: 532.58
Median: 578.0
Variance: 74011.14360000001
Standard Deviation: 272.04989174781895


62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [44]:
arr = np.random.randint(1, 101, size=50)
q1 = np.percentile(arr, 25)
q3 = np.percentile(arr, 75)
print("25th percentile:", q1)
print("75th percentile:", q3)

25th percentile: 19.0
75th percentile: 80.5


63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [46]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
correlation_coefficient = np.corrcoef(arr1, arr2)[0, 1]
print("Correlation coefficient:", correlation_coefficient)


Correlation coefficient: 0.9999999999999999


64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [47]:
m1= np.array([[1, 2], [3, 4]])
m2= np.array([[5, 6], [7, 8]])
np.dot(m1,m2)

array([[19, 22],
       [43, 50]])

65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [49]:
arr = np.random.randint(10, 1001, size=50)
arr_sorted = np.sort(arr)
q1 = np.percentile(arr, 10)
q2 = np.percentile(arr, 50)
q3 = np.percentile(arr, 90)
print("10th percentile:", q1)
print("50th (median) percentile:", q2)
print("90th percentile:", q3)


10th percentile: 136.10000000000002
50th (median) percentile: 536.5
90th percentile: 927.6


66. Create a NumPy array of integers and find the index of a specific element.

In [50]:
arr= np.array([1, 2, 3, 4, 5])
index = np.where(arr == 3)[0][0]
print("Index of the element:", index)

Index of the element: 2


67. Generate a random NumPy array and sort it in ascending order

In [53]:
arr = np.random.randint(1, 101, size=10)
sorted_arr = np.sort(arr)
print(arr)
print("Sorted array:", sorted_arr)

[42 66 56 29 25 92 40 98 98 62]
Sorted array: [25 29 40 42 56 62 66 92 98 98]


68. Filter elements >20  in the given NumPy array.

In [54]:
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_arr = arr[arr > 20]
print("Filtered array:", filtered_arr)

Filtered array: [25 42 30]


69. Filter elements which are divisible by 3 from a given NumPy array.

In [55]:
arr = np.array([1, 5, 8, 12, 15])
filtered_arr = arr[arr % 3 == 0]
print("Filtered array:", filtered_arr)

Filtered array: [12 15]


70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

In [56]:
arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print("Filtered array:", filtered_arr)

Filtered array: [20 30 40]


71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

In [57]:
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print("Byte order:", byte_order)

Byte order: =


72. For the given NumPy array, perform byte swapping in place using `byteswap()`.

In [58]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr_swapped = arr.byteswap()
print("Swapped array:", arr_swapped)

Swapped array: [16777216 33554432 50331648]


73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.

In [59]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr_swapped = arr.newbyteorder()
print("Swapped array:", arr_swapped)

Swapped array: [16777216 33554432 50331648]


74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.

In [60]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr_swapped = arr.newbyteorder()
print("Swapped array:", arr_swapped)

Swapped array: [16777216 33554432 50331648]


75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.

In [61]:
arr = np.array([1, 2, 3], dtype=np.int32)
byte_order = arr.dtype.byteorder
print("Byte order:", byte_order)

Byte order: =


76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [13]:
arr1 = np.array([range(1,11)])
copy_arr=arr1
copy_arr=copy_arr.astype("float")
print("arr1: ",arr1)
print("copy_arr: ",copy_arr)
# modification is not affection the previois array

arr1:  [[ 1  2  3  4  5  6  7  8  9 10]]
copy_arr:  [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]


77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [138]:
import random
arr_2d = np.random.randint(9,size=(3,3))
view_slice= arr_2d[:-1,:-1]
print(arr_2d)
print(view_slice)

[[7 6 4]
 [5 4 3]
 [5 4 0]]
[[7 6]
 [5 4]]


78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [133]:
array_a = np.array([range(1,13)])
array_a=array_a.reshape(4,3)
view_b = array_a[1:,1:]+5
print(array_a)
print(view_b)
# not altering the original array

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[10 11]
 [13 14]
 [16 17]]


79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [124]:
orig_array = np.array([[1,2],[3,4],[5,6],[7,8]])
reshaped_view = orig_array.T
reshaped_view=np.insert(reshaped_view,values=30,obj=(2),axis=0)
print(f"orig_array:\n{orig_array}\n reshaped_view: \n {reshaped_view}")
# it is not affecting the original array

orig_array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
 reshaped_view: 
 [[ 1  3  5  7]
 [ 2  4  6  8]
 [30 30 30 30]]


80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [120]:
data = np.random.random_integers(9,size=(3,4))
data_copy = data[data>5]
data_copy=np.insert(data_copy,values=30,obj=0)
print(f"data:\n{data}\ndata_copy:\n{data_copy}")

data:
[[1 3 4 8]
 [1 5 7 1]
 [7 5 4 6]]
data_copy:
[30  8  7  7  6]


81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [49]:
C=np.random.randint(5,size=(3,2))
D= np.random.randint(9,size=(3,2))
print(f"Addition:\n{C}\n+\n{D}\n=\n{C+D}")
print(f"Subtraction:\n{C}\n-\n{D}\n=\n{C-D}")

Addition:
[[1 0]
 [1 2]
 [3 1]]
+
[[7 7]
 [6 7]
 [5 3]]
=
[[8 7]
 [7 9]
 [8 4]]
Subtraction:
[[1 0]
 [1 2]
 [3 1]]
-
[[7 7]
 [6 7]
 [5 3]]
=
[[-6 -7]
 [-5 -5]
 [-2 -2]]


82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [54]:
C=np.random.randint(5,size=(3,2))
D= np.random.randint(9,size=(2,4))
C@D

array([[24,  4,  6, 40],
       [16,  6,  9, 36],
       [ 8,  8, 12, 32]])

83. Create a matrix `E` and find its transpose.

In [39]:
E = np.random.randint(7,size=(2,3))
print("E:\n",E)
print("Transpose of E:\n",np.transpose(E))

E:
 [[3 5 0]
 [1 6 0]]
Transpose of E:
 [[3 1]
 [5 6]
 [0 0]]


84. Generate a square matrix `F` and compute its determinant.

In [35]:
F = np.random.randint(5,size=(3,3))
print("metrix :\n",F)
print("determinant of square-metrix ",np.linalg.det(F))

metrix :
 [[0 4 3]
 [2 0 0]
 [2 4 4]]
determinant of square-metrix  -7.999999999999998


85. Create a square matrix `G` and find its inverse.

In [34]:
G = np.random.randint(5,size=(3,3))
inverse_square_metrix = np.linalg.inv(G)
print(G)
print(inverse_square_metrix)

[[0 0 2]
 [4 3 2]
 [1 3 0]]
[[-0.33333333  0.33333333 -0.33333333]
 [ 0.11111111 -0.11111111  0.44444444]
 [ 0.5         0.          0.        ]]
